### ISSUE TITLE
Distorted hearts

### ISSUE THREAD

**Issue by CybertronicToon** [videoerror/SurvivalTest-M0d#1]
The hearts get distorted based off of the size of the window. On the default square window: 
![image](https://cloud.githubusercontent.com/assets/6559043/21959196/6bec367e-da85-11e6-8dae-5596b43a90f7.png)

Notice how all of the pixels of the heart do not have the exact same amount of pixels. This leads to it looking distorted. All of the pixels in the texture should always have the exact same amount of pixels on-screen representing them, rather than some being four,, some being six, etc..

**Comment by videoerror** [comment]
They look properly scaled to me?

**Comment by CybertronicToon** [comment]
![heartbug4x](https://cloud.githubusercontent.com/assets/6559043/21959281/c133d1ee-da87-11e6-9e45-6889017cb922.png)

Notice the black pixels where I circled. They are all one pixel in the texture, yet they are all different sizes. In MineCraft, these would all be the same size.

**Comment by videoerror** [comment]
Hmm. Not sure why this appears to occur, let me look into this. This could easily be due to me incorrectly grabbing the coordinates to the texture in the icons.png image then stretching them accidentally.

**Comment by Cheesse** [comment]
Try changing the Hotbar Scale setting in the options menu.
